### ISSUE TITLE
初始化时调用 setCachedIpEnable 会闪退

### ISSUE THREAD

**Issue by 2015-D33** [TencentCloud/httpdns-sdk-android#30]
FATAL EXCEPTION: dns-work-1
                                                                                                    Process: com.yx.dnsTest, PID: 9637
                                                                                                    java.lang.NoSuchMethodError: No static method query(Landroidx/room/RoomDatabase;Landroidx/sqlite/db/SupportSQLiteQuery;ZLandroid/os/CancellationSignal;)Landroid/database/Cursor; in class Landroidx/room/util/DBUtil; or its super classes (declaration of 'androidx.room.util.DBUtil' appears in /data/app/~~GOwx0411BNrG2P-hBr3jvQ==/com.yx.dnsTest-Co1mRExMCARJGa3CNeKq1Q==/base.apk)
                                                                                                    	at com.tencent.msdk.dns.DnsService$b.run(DnsService.java:194)
                                                                                                    	at a.a.a.a.c.b.a.run(DnsExecutors.java:10)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1015)

**Comment by lemondark** [comment]
将在下个版本修复。

**Comment by lemondark** [comment]
已解决
